### PR TITLE
Renaming LG -> HLG

### LINKED ISSUE #121: Issue in naming: LG vs HLG
I was explaining snowfall's approach to decoding to somebody and I realized that what we call "LG" might actually be "HLG", because the actual LG is composed with `ctc_topo` (our `H`); see e.g. in the following contexts:

https://github.com/k2-fsa/snowfall/blob/master/snowfall/decoding/graph.py#L66
https://github.com/k2-fsa/snowfall/blob/master/egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py#L71

If you agree with that I will rename it.

### PR DESCRIPTION
**Pull request by pzelasko**
Resolves #121

### CODE REVIEW

**Comment by pzelasko** [comment]
@danpovey @csukuangfj LMK if I can merge it.

**Comment by csukuangfj** [comment]
Thanks! +2

**Comment by xiaohui-zhang** [comment]
nit: calling it TLG (T: topo) might be better since the we don't call "ctc_topo" FST H.fst explicitly. Also it'll be less confusing in case later on we want to compare different label topologies where H.fst really means HMM.

**Comment by danpovey** [comment]
@xiaohui-zhang  We spoke about this issue before; I felt H was better because not everyone has used Eesen so knows the T terminology.  Also I do regard the CTC topology as just a specific kind of H, rather than a special different thing.

**Pull request merged**
