### PR TITLE
Sync with Lhotse's speed perturbation fix

### PR DESCRIPTION
**Pull request by pzelasko**

### CODE REVIEW

**Comment by pzelasko** [comment]
It runs alright for me, and the model is converging as usual with the first couple hundred of batches. I'm merging - please update your Lhotse to the latest master branch before you attempt to run.

**Comment by danpovey** [comment]
Great!  Do we have to rerun prepare.py in snowfall to get the benefit of
this, and if we don't, will it still run?

**Comment by pzelasko** [comment]
You have to re-run to get the benefit; it will still run if you don't.

**Comment by pzelasko** [comment]
(disambiguation: the training will still run with old prepare.py output; new prepare.py won't run with older Lhotse)

**Pull request merged**
