### PR TITLE
sync snowfall with k2 change

### PR DESCRIPTION
**Pull request by qindazhu**
This PR should be merged when https://github.com/k2-fsa/k2/pull/587 get merged as there's some API changes in k2 (actually only `get_tot_scores`)

 Wondering what python formatter you guys use, seems there's a lot of automatic style changes at my side...

### CODE REVIEW

**Comment by danpovey** [comment]
Isn't it possible to disable automatic formatting of lines that weren't touched?

**Comment by csukuangfj** [comment]
:NoAutoFormatBuffer can disable auto format on save.

:AutoFormatBuffer enables it.

:FormatLine is able to format a selected range when auto format is disabled.






Friday, 15 January 2021, 19:47 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by qindazhu** [comment]
OK, style changes reverted.

**Comment by csukuangfj** [comment]
+2

ready to merge

**Pull request merged**
