### PR TITLE
Constructing ctc decoding graph in a batch

### PR DESCRIPTION
**Pull request by pkufool**
See comments #220 

> Thanks for doing the comparison, and sure, that's a good idea. Yes, we should introduce a special-purpose function that constructs a batch of CTC graphs from a ragged tensor consisting of the linear symbol sequences for each one. 

Current functions in k2 support to construct ctc decoding graph in a batch, so I think there is no other things should be done in C++ side. Fix me if I understand in a wrong way.

### CODE REVIEW

**Comment by danpovey** [comment]
I think we were talking about doing it in a single function, rather than a sequence of functions.
BTW, we'd have to decide which type of topology to use, in terms of how it deals with repeats of the same
symbol (i.e. do we require a blank in between?).  If we require a blank in between those repeats, the code 
becomes a little more complicated.

**Comment by pkufool** [comment]
> I think we were talking about doing it in a single function, rather than a sequence of functions.
> BTW, we'd have to decide which type of topology to use, in terms of how it deals with repeats of the same
> symbol (i.e. do we require a blank in between?). If we require a blank in between those repeats, the code
> becomes a little more complicated.

**Comment by pkufool** [comment]
I see,  so we will implement a function in k2 that given a lexicon fsa and ragged tensor consisting of the linear symbol sequences as input and return the ctc graph.

**Comment by danpovey** [comment]
No, it would take just a sequence of phone symbols (or whatever symbols the user is using, not necessarily worsd), 
and return the linear CTC graph; I think that is his scenario.  This would not support optional silences.

**Comment by pkufool** [comment]
Implements in the c++ side, see https://github.com/k2-fsa/k2/pull/776

**Pull request closed without merging**
