### PR TITLE
Misc. script change...

### PR DESCRIPTION
**Pull request by danpovey**
s

### CODE REVIEW

**Comment by danpovey** [comment]
Most of these changes are for debugging and likely not important, but I'm just making a PR for reference as others might want to reproduce what I did; I got 16% WER.   This is after the changes to k2 in https://github.com/k2-fsa/k2/pull/517.
Actually the key part of what I did is essentially to work around a compiler bug, as far as I can tell (grr).  I'll try to confirm this in future.
```
ref= ['MUSSULMANS', 'AND', 'GIAOURS', 'THROW', 'KERCHIEFS', 'AT', 'A', 'SMILE', 'AND', 'HAVE', 'NO', 'RUTH', 'FOR', 'ANY', 'WEEPING']
hyp= ['THE', 'SUMMONS', 'AND', 'GUNNERS', 'THOUGH', 'CURTIS', 'AND', 'HIS', 'SMILE', 'AND', 'HAVE', 'NO', 'ROOF', 'FOR', 'ANY', 'WEEPING']
ref= ['AND', 'THOUGH', 'I', 'HAVE', 'GROWN', 'SERENE', 'AND', 'STRONG', 'SINCE', 'THEN', 'I', 'THINK', 'THAT', 'GOD', 'HAS', 'WILLED', 'A', 'STILL', 'RENEWABLE', 'FEAR']
hyp= ['AND', 'THOUGH', 'I', 'HAVE', 'GROWN', 'SERENE', 'AND', 'STRONG', 'SINCE', 'THEN', 'I', 'THINK', 'THAT', 'GOD', 'HAS', 'WILLED', 'A', 'STILL', 'RENEWABLE', 'FEAR']
ref= ['IF', 'HE', 'TO', 'KEEP', 'ONE', 'OATH', 'MUST', 'LOSE', 'ONE', 'JOY', 'BY', 'HIS', "LIFE'S", 'STAR', 'FORETOLD']
hyp= ['IF', 'HE', 'TO', 'KEEP', 'ON', 'ALL', 'MUST', 'LOSE', 'WHAT', 'ENJOY', 'BY', 'HIS', "WIFE'S", 'STORE', 'FOR', 'TOLL']
ref= ['A', 'RING', 'OF', 'AMETHYST', 'I', 'COULD', 'NOT', 'WEAR', 'HERE', 'PLAINER', 'TO', 'MY', 'SIGHT', 'THAN', 'THAT', 'FIRST', 'KISS']
hyp= ['THE', 'RING', 'OF', 'AMETHYST', 'I', 'COULD', 'NOT', 'WEAR', 'HE', 'PLAYED', 'INTO', 'MY', 'SIGHT', 'THEN', 'THAT', 'FIRST', 'KIPPS']
ref= ['I', 'LOVE', 'THEE', 'WITH', 'THE', 'PASSION', 'PUT', 'TO', 'USE', 'IN', 'MY', 'OLD', 'GRIEFS', 'AND', 'WITH', 'MY', "CHILDHOOD'S", 'FAITH']
hyp= ['I', 'LOVE', 'THEE', 'WITH', 'THE', 'PASSION', 'PUT', 'TO', 'USE', 'IN', 'MY', 'OLD', 'GREASIN', 'WITH', 'MY', "CHILDHOOD'S", 'FAITH']
ref= ['DEAREST', 'TEACH', 'ME', 'SO', 'TO', 'POUR', 'OUT', 'GRATITUDE', 'AS', 'THOU', 'DOST', 'GOOD']
hyp= ['DEAREST', 'TEACH', 'ME', 'SO', 'TO', 'POUR', 'OUT', 'GRATITUDE', 'AS', 'THOU', 'DOST', 'GOODT']
ref= ['SLOW', 'TO', 'WORLD', 'GREETINGS', 'QUICK', 'WITH', 'ITS', 'O', 'LIST', 'WHEN', 'THE', 'ANGELS', 'SPEAK']
hyp= ['SLOW', 'TO', 'WORLD', 'GREETINGS', 'QUICK', 'WITH', 'ITS', 'OLD', 'LIST', 'WHEN', 'THE', 'ANGEL', 'SPEAK']
ref= ['I', 'THANK', 'ALL', 'WHO', 'HAVE', 'LOVED', 'ME', 'IN', 'THEIR', 'HEARTS', 'WITH', 'THANKS', 'AND', 'LOVE', 'FROM', 'MINE']
hyp= ['I', 'THINK', 'ALL', 'WHO', 'HAVE', 'LEFT', 'ME', 'IN', 'THEIR', 'HEARTS', 'WITH', 'THANKS', 'AND', 'LOVE', 'FROM', 'MINE']
ref= ['BUT', 'THOU', 'ART', 'NOT', 'SUCH', 'A', 'LOVER', 'MY', 'BELOVED']
hyp= ['BUT', 'THOU', 'ART', 'NOT', 'SUCH', 'A', 'LETTER', 'MY', 'BELOVED']
ref= ['O', 'LOVE', 'O', 'TROTH']
hyp= ['ALL', 'OF', 'A', 'TROUGH']
ref= ['AND', 'LOVE', 'BE', 'FALSE']
hyp= ['AND', 'THE', 'LOVE', 'BE', 'FALSE']
%WER 16.82% [8844 / 52576, 1047 ins, 1033 del, 6764 sub ]

```

**Comment by danpovey** [comment]
.. in terms of changes to snowfall, the beam changes may be the only significant thing.
When I revert the search_beam from 20 to 10, the WER increases from 16% to 39%, mostly due to more deletions.
It seems it has trouble reaching the end-state of the graph at lower beams.

**Comment by csukuangfj** [comment]
I am able to reproduce the result.

**Comment by pzelasko** [comment]
I got 40% but I’ll re-run the whole thing from scratch and then see again.

**Comment by danpovey** [comment]
A caution: I didn't test the change to the graph.py script where I remove
the epsilons from aux_labels.  But I also do the same thing in decode.py
so I'm pretty sure it shouldn't change anything.'

Did you rerun just the decoding, and did you see anything odd in the
results?

**Comment by pzelasko** [comment]
It is now: ```%WER 17.42% [9161 / 52576, 1076 ins, 1111 del, 6974 sub ]```

Previously I ran everything from the `prepare.py` step, but had a pretty old L and G dumped on disk. Maybe there were some significant changes in their construction in the meanwhile (or the K2 code responsible for it).

**Comment by csukuangfj** [comment]
There are conflicts.

**Comment by danpovey** [comment]
Ah.. this is not for merge now, will close.

**Pull request closed without merging**
