### PR TITLE
Add dev-other and test-other to librispeech recipe

### PR DESCRIPTION
**Pull request by pzelasko**
Note: this is un-tested yet, I'll run it once I'm able to...

### CODE REVIEW

**Comment by danpovey** [comment]
Great!   I'll wait for you to test before merging..

**Comment by pzelasko** [comment]
The servers where I have my recently-trained models are currently down; if you need this quickly then you might need to try it out yourself for now 😕

**Comment by danpovey** [comment]
When I tested an already-trained model with this (trained with an older version of the code), I got 11% on test-clean where I should have got around 7%.  I wonder if there might have been any change that could be responsible for this, e.g. some code fix about the attention mask?
I don't think it's about this PR, I don't see anything that would affect this.

**Comment by danpovey** [comment]
The WER regression wasn't to do with this, and this works otherwise, so merging.

**Comment by pzelasko** [comment]
Interesting, I will check as soon as I have access to my models again.

**Comment by pzelasko** [comment]
I checked out this branch and ran with lhotse before the latest bug-fixes; got WER 6.82% on test-clean, with a conformer model trained ~a week ago. Then I checked out latest lhotse and got the same number. Then, I updated K2 to the latest version and it's still the same number. I have no idea where the regression you reported comes from.

**Comment by danpovey** [comment]
It's OK about the regression, I think it's a problem with a model I trained a very long time ago.

**Pull request merged**
