### PR TITLE
transformer train/decode scripts for aishell

### PR DESCRIPTION
**Pull request by hegc**

### CODE REVIEW

**Comment by danpovey** [comment]
Thanks!

Does anyone have time to see if they can reproduce this problem on our cluster?

**Comment by csukuangfj** [comment]
I am going to try to reproduce it on our server.

**Comment by csukuangfj** [comment]
Got the following error with the latest master of k2 and lhotse, indicating possibly a bug somewhere in k2.

```
2021-03-02 15:04:52,891 INFO [mmi_att_transformer_train.py:298]
batch 90, epoch 0/20 global average objf: 1.515463 over 445070.0 frames (100.0% kept), 
current batch average objf: 1.349802 over 4853 frames (100.0% kept) avg time waiting for batch 0.020s

Traceback (most recent call last):
  File "./mmi_att_transformer_train.py", line 617, in <module>
    main()
  File "./mmi_att_transformer_train.py", line 545, in main
    objf, valid_objf, global_batch_idx_train = train_one_epoch(
  File "./mmi_att_transformer_train.py", line 277, in train_one_epoch
    curr_batch_objf, curr_batch_frames, curr_batch_all_frames = get_objf(
  File "./mmi_att_transformer_train.py", line 140, in get_objf
    den_tot_scores = den.get_tot_scores(
  File "/root/fangjun/open-source/k2/k2/python/k2/fsa.py", line 598, in get_tot_scores
    tot_scores = k2.autograd._GetTotScoresFunction.apply(
  File "/root/fangjun/open-source/k2/k2/python/k2/autograd.py", line 49, in forward
    tot_scores = fsas._get_tot_scores(use_double_scores=use_double_scores,
  File "/root/fangjun/open-source/k2/k2/python/k2/fsa.py", line 577, in _get_tot_scores
    forward_scores = self._get_forward_scores(use_double_scores,
  File "/root/fangjun/open-source/k2/k2/python/k2/fsa.py", line 527, in _get_forward_scores
    entering_arc_batches=self._get_entering_arc_batches(),
  File "/root/fangjun/open-source/k2/k2/python/k2/fsa.py", line 467, in _get_entering_arc_batches
    incoming_arcs=self._get_incoming_arcs(),
  File "/root/fangjun/open-source/k2/k2/python/k2/fsa.py", line 453, in _get_incoming_arcs
    cache[name] = _k2.get_incoming_arcs(self.arcs,
RuntimeError: CUDA out of memory. Tried to allocate 17179869182.06 GiB (GPU 0; 31.75 GiB total capacity; 16.12 GiB already allocated;
9.93 GiB free; 20.60 GiB reserved in total by PyTorch)
```

And the error logs for the second and third run are

```
2021-03-02 15:09:29,257 INFO [mmi_att_transformer_train.py:298] 
batch 90, epoch 0/20 global average objf: 1.515499 over 445070.0 frames (100.0% kept),
current batch average objf: 1.349712 over 4853 frames (100.0% kept) avg time waiting for batch 0.020s

Traceback (most recent call last):
  File "./mmi_att_transformer_train.py", line 617, in <module>
    main()
  File "./mmi_att_transformer_train.py", line 545, in main
    objf, valid_objf, global_batch_idx_train = train_one_epoch(
  File "./mmi_att_transformer_train.py", line 277, in train_one_epoch
    curr_batch_objf, curr_batch_frames, curr_batch_all_frames = get_objf(
  File "./mmi_att_transformer_train.py", line 135, in get_objf
    den = k2.intersect_dense(den, dense_fsa_vec, 10.0)
  File "/root/fangjun/open-source/k2/k2/python/k2/autograd.py", line 768, in intersect_dense
    _IntersectDenseFunction.apply(a_fsas, b_fsas, out_fsa, output_beam,
  File "/root/fangjun/open-source/k2/k2/python/k2/autograd.py", line 538, in forward
    ragged_arc, arc_map_a, arc_map_b = _k2.intersect_dense(
RuntimeError: CUDA out of memory. Tried to allocate 4.12 GiB (GPU 0; 31.75 GiB total capacity; 22.35 GiB already allocated; 3.51 GiB f
ree; 27.01 GiB reserved in total by PyTorch)
```

and

```
2021-03-02 15:11:33,515 INFO [mmi_att_transformer_train.py:298] 
batch 90, epoch 0/20 global average objf: 1.515469 over 445070.0 frames (100.0% kept),
current batch average objf: 1.349761 over 4853 frames (100.0% kept) avg time waiting for batch 0.021s

Traceback (most recent call last):
  File "./mmi_att_transformer_train.py", line 617, in <module>
    main()
  File "./mmi_att_transformer_train.py", line 545, in main
    objf, valid_objf, global_batch_idx_train = train_one_epoch(
  File "./mmi_att_transformer_train.py", line 277, in train_one_epoch
    curr_batch_objf, curr_batch_frames, curr_batch_all_frames = get_objf(
  File "./mmi_att_transformer_train.py", line 135, in get_objf
    den = k2.intersect_dense(den, dense_fsa_vec, 10.0)
  File "/root/fangjun/open-source/k2/k2/python/k2/autograd.py", line 768, in intersect_dense
    _IntersectDenseFunction.apply(a_fsas, b_fsas, out_fsa, output_beam,
  File "/root/fangjun/open-source/k2/k2/python/k2/autograd.py", line 538, in forward
    ragged_arc, arc_map_a, arc_map_b = _k2.intersect_dense(
RuntimeError: CUDA out of memory. Tried to allocate 4.12 GiB (GPU 0; 31.75 GiB total capacity; 22.35 GiB already allocated; 3.51 GiB free; 27.02 GiB reserved in total by PyTorch)
```

---

The following is the diff between this pullrequest and the latest master to fix the subsequent error

```
diff --git a/egs/aishell/asr/simple_v1/mmi_att_transformer_train.py b/egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
index 8bff576..969c350 100644
--- a/egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
+++ b/egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
@@ -101,12 +101,12 @@ def get_objf(batch: Dict,
     # at entry, feature is [N, T, C]
     feature = feature.permute(0, 2, 1)  # now feature is [N, C, T]
     if is_training:
-        nnet_output, encoder_memory, memory_mask = model(feature, supervision_segments)
+        nnet_output, encoder_memory, memory_mask = model(feature, supervisions)
         if att_rate != 0.0:
             att_loss = model.decoder_forward(encoder_memory, memory_mask, supervisions, graph_compiler)
     else:
         with torch.no_grad():
-            nnet_output, encoder_memory, memory_mask = model(feature, supervision_segments)
+            nnet_output, encoder_memory, memory_mask = model(feature, supervisions)
             if att_rate != 0.0:
                 att_loss = model.decoder_forward(encoder_memory, memory_mask, supervisions, graph_compiler)
```

```
2021-03-02 14:51:11,820 INFO [mmi_att_transformer_train.py:544] epoch 0, learning rate 0
Traceback (most recent call last):
  File "./mmi_att_transformer_train.py", line 617, in <module>
    main()
  File "./mmi_att_transformer_train.py", line 545, in main
    objf, valid_objf, global_batch_idx_train = train_one_epoch(
  File "./mmi_att_transformer_train.py", line 277, in train_one_epoch
    curr_batch_objf, curr_batch_frames, curr_batch_all_frames = get_objf(
  File "./mmi_att_transformer_train.py", line 104, in get_objf
    nnet_output, encoder_memory, memory_mask = model(feature, supervision_segments)
  File "/root/fangjun/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/fangjun/open-source/snowfall/snowfall/models/transformer.py", line 92, in forward
    encoder_memory, memory_mask = self.encode(x, supervision)
  File "/root/fangjun/open-source/snowfall/snowfall/models/transformer.py", line 111, in encode
    mask = encoder_padding_mask(supervisions)
  File "/root/fangjun/open-source/snowfall/snowfall/models/transformer.py", line 584, in encoder_padding_mask
    (supervisions['sequence_idx'],
IndexError: too many indices for tensor of dimension 2
```

**Comment by danpovey** [comment]
If we reverted the following differences:
```
<         if batch_idx > 0 and batch_idx % 1000 == 0:
---
>         if batch_idx > 0 and batch_idx % 200 == 0:
362c359
<         default=20000,
---
>         default=50000,
```
it would clarify how soon it fails, and also whether it could be a batch-size issue.

**Comment by danpovey** [comment]
See this
https://medium.com/zendesk-engineering/hunting-for-memory-leaks-in-python-applications-6824d0518774
and search for `heap dump`.. I think doing this after some number of iterations that's less than the number it fails at, would help narrow it down.

**Comment by csukuangfj** [comment]
thanks, trying it.

**Comment by csukuangfj** [comment]
@hegc 
Please have a look at https://github.com/hegc/snowfall/pull/1

It reduces `max-frames` to `10000`.  The training is still running after the 0th epoch and I don't see a 
significant GPU RAM consumption with `watch nvidia-smi`.

**Comment by hegc** [comment]
When max-frames is 10000, the training process will stop in 3th epoch because of OOM.

**Comment by danpovey** [comment]
Looking at the stack trace in pdb, it seems it is failing in intersect_dense().  Because the num-phones is quite a bit larger in aishell than in librispeech, I think the dense intersection is using more memory.  I'm trying to find out more.

**Comment by danpovey** [comment]
OK, it looks like what happened is that an intermediate quantity formed while creating the product of intersect_dense with the den graph was extremely large.  I'll have to rewrite the algorithm a little bit to minimize memory use in the final stage.


I think the issue is that near the beginning of training, the model outputs are small so pruning removes fewer arcs.
When I reduce the beam from 10.0 to 5.0 it seems to run further but also stops

**Pull request merged**
