### PR TITLE
Support using k2.intersect_dense_pruned in computing LF-MMI loss.

### PR DESCRIPTION
**Pull request by csukuangfj**
Relates https://github.com/k2-fsa/k2/issues/739

@jarvan-Wang

Could you try this pull request?

Please add the following command-line option while running the script:
```
--use-pruned-intersect=1
```

---

From https://github.com/k2-fsa/k2/issues/739#issuecomment-843077996

> or to do the den decoding separately from the num
forward-backward with intersect_dense_pruned() which allows you to use a
single FSA instead of
multiple FSAs.  That would also be more suitable since the den graph is too
large.
Fangjun, at some point we should probably create an option in the training
code (or simply an alternative code path) which is efficient
when the den graph is inconveniently large.

An option is added to let the user make the decision whether the graph is large or not.

---

I only run the script for 100 batches and the loss is decreasing as expected, so I think it is safe to merge.

### CODE REVIEW

**Comment by csukuangfj** [comment]
Here are the logs with/without `--use-pruned-intersect` for the first 100 batches.
Notice that `--use-pruned-intersect=1` has a slightly lower objf.

## --use-pruned-intersect=1
```
./mmi_att_transformer_train.py  --full-libri=False --use-ali-model=0 --use-pruned-intersect=1

2021-05-19 14:49:10,994 INFO [mmi_att_transformer_train.py:273] (0/1) batch 0, epoch 0/10 global average objf: 1.768724 over 12313.0 fr
ames (100.0% kept), current batch average objf: 1.768724 over 12313 frames (100.0% kept) avg time waiting for batch 28.880s
2021-05-19 14:49:11,011 INFO [distributed.py:607] (0/1) Reducer buckets have been rebuilt in this iteration.
2021-05-19 14:49:18,814 INFO [mmi_att_transformer_train.py:273] (0/1) batch 10, epoch 0/10 global average objf: 1.784099 over 135096.0
frames (100.0% kept), current batch average objf: 1.734967 over 12221 frames (100.0% kept) avg time waiting for batch 2.894s
2021-05-19 14:49:27,070 INFO [mmi_att_transformer_train.py:273] (0/1) batch 20, epoch 0/10 global average objf: 1.742342 over 257832.0
frames (100.0% kept), current batch average objf: 1.633413 over 12157 frames (100.0% kept) avg time waiting for batch 1.450s
2021-05-19 14:49:36,043 INFO [mmi_att_transformer_train.py:273] (0/1) batch 30, epoch 0/10 global average objf: 1.708514 over 380360.0
frames (100.0% kept), current batch average objf: 1.653877 over 12173 frames (100.0% kept) avg time waiting for batch 0.969s
2021-05-19 14:49:46,012 INFO [mmi_att_transformer_train.py:273] (0/1) batch 40, epoch 0/10 global average objf: 1.701181 over 503900.0
frames (100.0% kept), current batch average objf: 1.692598 over 12358 frames (100.0% kept) avg time waiting for batch 0.729s
2021-05-19 14:49:55,149 INFO [mmi_att_transformer_train.py:273] (0/1) batch 50, epoch 0/10 global average objf: 1.670231 over 626743.0
frames (100.0% kept), current batch average objf: 1.521726 over 12147 frames (100.0% kept) avg time waiting for batch 0.585s
2021-05-19 14:50:04,167 INFO [mmi_att_transformer_train.py:273] (0/1) batch 60, epoch 0/10 global average objf: 1.638435 over 749187.0
frames (100.0% kept), current batch average objf: 1.490543 over 12147 frames (100.0% kept) avg time waiting for batch 0.488s
2021-05-19 14:50:13,162 INFO [mmi_att_transformer_train.py:273] (0/1) batch 70, epoch 0/10 global average objf: 1.610674 over 871675.0
frames (100.0% kept), current batch average objf: 1.383189 over 12154 frames (100.0% kept) avg time waiting for batch 0.420s
2021-05-19 14:50:22,283 INFO [mmi_att_transformer_train.py:273] (0/1) batch 80, epoch 0/10 global average objf: 1.583727 over 994877.0
frames (100.0% kept), current batch average objf: 1.377218 over 12259 frames (100.0% kept) avg time waiting for batch 0.368s
2021-05-19 14:50:31,331 INFO [mmi_att_transformer_train.py:273] (0/1) batch 90, epoch 0/10 global average objf: 1.561083 over 1117441.0
 frames (100.0% kept), current batch average objf: 1.425102 over 12328 frames (100.0% kept) avg time waiting for batch 0.328s
2021-05-19 14:50:40,221 INFO [mmi_att_transformer_train.py:273] (0/1) batch 100, epoch 0/10 global average objf: 1.537064 over 1240513.
0 frames (100.0% kept), current batch average objf: 1.296827 over 12208 frames (100.0% kept) avg time waiting for batch 0.296s
```

## --use-pruned-intersect=0
```
./mmi_att_transformer_train.py --full-libri=False --use-ali-model=0 --use-pruned-intersect=0

2021-05-19 13:00:35,449 INFO [mmi_att_transformer_train.py:275] (0/1) batch 0, epoch 0/10 global average objf: 1.786543 over 12313.0 frames (100.0% kept), current batch average objf: 1.786542 over 12313 frames (100.0% kept) avg time waiting for batch 29.168s
2021-05-19 13:00:35,466 INFO [distributed.py:607] (0/1) Reducer buckets have been rebuilt in this iteration.
2021-05-19 13:00:42,162 INFO [mmi_att_transformer_train.py:275] (0/1) batch 10, epoch 0/10 global average objf: 1.807433 over 135096.0
frames (100.0% kept), current batch average objf: 1.756499 over 12221 frames (100.0% kept) avg time waiting for batch 2.923s
2021-05-19 13:00:49,305 INFO [mmi_att_transformer_train.py:275] (0/1) batch 20, epoch 0/10 global average objf: 1.766658 over 257832.0
frames (100.0% kept), current batch average objf: 1.653667 over 12157 frames (100.0% kept) avg time waiting for batch 1.465s
2021-05-19 13:00:56,932 INFO [mmi_att_transformer_train.py:275] (0/1) batch 30, epoch 0/10 global average objf: 1.725723 over 380360.0
frames (100.0% kept), current batch average objf: 1.635614 over 12173 frames (100.0% kept) avg time waiting for batch 0.979s
2021-05-19 13:01:05,346 INFO [mmi_att_transformer_train.py:275] (0/1) batch 40, epoch 0/10 global average objf: 1.711869 over 503900.0
frames (100.0% kept), current batch average objf: 1.687513 over 12358 frames (100.0% kept) avg time waiting for batch 0.736s
2021-05-19 13:01:13,305 INFO [mmi_att_transformer_train.py:275] (0/1) batch 50, epoch 0/10 global average objf: 1.677409 over 626743.0
frames (100.0% kept), current batch average objf: 1.522647 over 12147 frames (100.0% kept) avg time waiting for batch 0.590s
2021-05-19 13:01:20,845 INFO [mmi_att_transformer_train.py:275] (0/1) batch 60, epoch 0/10 global average objf: 1.641111 over 749187.0
frames (100.0% kept), current batch average objf: 1.465976 over 12147 frames (100.0% kept) avg time waiting for batch 0.493s
2021-05-19 13:01:28,464 INFO [mmi_att_transformer_train.py:275] (0/1) batch 70, epoch 0/10 global average objf: 1.612189 over 871675.0
frames (100.0% kept), current batch average objf: 1.394416 over 12154 frames (100.0% kept) avg time waiting for batch 0.423s
2021-05-19 13:01:36,341 INFO [mmi_att_transformer_train.py:275] (0/1) batch 80, epoch 0/10 global average objf: 1.584267 over 994877.0
frames (100.0% kept), current batch average objf: 1.368041 over 12259 frames (100.0% kept) avg time waiting for batch 0.371s
2021-05-19 13:01:44,179 INFO [mmi_att_transformer_train.py:275] (0/1) batch 90, epoch 0/10 global average objf: 1.562747 over 1117441.0 frames (100.0% kept), current batch average objf: 1.432522 over 12328 frames (100.0% kept) avg time waiting for batch 0.331s
2021-05-19 13:01:52,076 INFO [mmi_att_transformer_train.py:275] (0/1) batch 100, epoch 0/10 global average objf: 1.539240 over 1240513.0 frames (100.0% kept), current batch average objf: 1.308250 over 12208 frames (100.0% kept) avg time waiting for batch 0.298s
```

**Comment by Jarvan-Wang** [comment]
ok, I'm on it

**Comment by Jarvan-Wang** [comment]
I rerun my model(output Character rather than Phone!) training recipe, got:
```
[nmyjs_160_37] 2021-05-19 15:19:39,880 (lexicon:19) INFO: Loading L.fst
[New Thread 0x7faf02a0d700 (LWP 21585)]
[New Thread 0x7faf0220c700 (LWP 21586)]
[F] [F] [F] [F] [F] [F] /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void /search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678:lambda [](int)->void::operator()(int)->void block:[71,0,0], thread: [115,0,0] block:[53,0,0], thread: [150,0,0] block:[89,0,0], thread: [80,0,0] block:[107,0,0], thread: [45,0,0] block:[17,0,0], thread: [220,0,0] block:[35,0,0], thread: [185,0,0] Check failed: Check failed: Check failed: Check failed: Check failed: Check failed: static_cast<uint32_t>(scores_idx2)static_cast<uint32_t>(scores_idx2)static_cast<uint32_t>(scores_idx2)static_cast<uint32_t>(scores_idx2)static_cast<uint32_t>(scores_idx2)static_cast<uint32_t>(scores_idx2)      <<<<<<      static_cast<uint32_t>(scores_num_cols)static_cast<uint32_t>(scores_num_cols)static_cast<uint32_t>(scores_num_cols)static_cast<uint32_t>(scores_num_cols)static_cast<uint32_t>(scores_num_cols)static_cast<uint32_t>(scores_num_cols) ( ( ( (4574 ( (457445744574 vs. 45744574 vs.  vs. 4574 vs.  vs.  vs. 45744574) 45744574) 4574
) )
) )



/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [71,0,0], thread: [115,0,0] Assertion `Some bad things happened` failed.
/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [53,0,0], thread: [150,0,0] Assertion `Some bad things happened` failed.
/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [107,0,0], thread: [45,0,0] Assertion `Some bad things happened` failed.
/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [89,0,0], thread: [80,0,0] Assertion `Some bad things happened` failed.
/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [17,0,0], thread: [220,0,0] Assertion `Some bad things happened` failed.
/search/odin/wangjiawen/k2/k2/csrc/intersect_dense_pruned.cu:678: lambda [](int)->void::operator()(int)->void: block: [35,0,0], thread: [185,0,0] Assertion `Some bad things happened` failed.
[F] /search/odin/wangjiawen/k2/k2/csrc/array.h:329:T k2::Array1<T>::operator[](int32_t) const [with T = int; int32_t = int] Check failed: ret == cudaSuccess (710 vs. 0)  Error: device-side assert triggered.


[ Stack-Trace: ]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2_log.so(k2::internal::GetStackTrace()+0x46) [0x7faf547bc77d]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::internal::Logger::~Logger()+0x35) [0x7faf54f16dd9]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::Array1<int>::operator[](int) const+0x56c) [0x7faf54f1b976]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::Array1<int>::Back() const+0x130) [0x7faf54f18e70]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::Renumbering::ComputeOld2New()+0xe0) [0x7faf54f14630]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::Renumbering::NumNewElems()+0x43) [0x7faf55074873]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(std::unique_ptr<k2::MultiGraphDenseIntersectPruned::FrameInfo, std::default_delete<k2::MultiGraphDenseIntersectPruned::FrameInfo> > k2::MultiGraphDenseIntersectPruned::PropagateForward<32>(int, k2::MultiGraphDenseIntersectPruned::FrameInfo*)+0x534) [0x7faf5507e04c]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::MultiGraphDenseIntersectPruned::Intersect()+0x20d) [0x7faf55075c97]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/libk2context.so(k2::IntersectDensePruned(k2::Ragged<k2::Arc>&, k2::DenseFsaVec&, float, float, int, int, k2::Ragged<k2::Arc>*, k2::Array1<int>*, k2::Array1<int>*)+0xb5) [0x7faf5506de65]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0xc4bfd) [0x7faf59dcbbfd]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0xce6d7) [0x7faf59dd56d7]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0xcd6b6) [0x7faf59dd46b6]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0xcb063) [0x7faf59dd2063]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0xcb0ed) [0x7faf59dd20ed]
/search/odin/wangjiawen/espnet2_500h_charlevel_mmi/lib/_k2.cpython-37m-x86_64-linux-gnu.so(+0x522ef) [0x7faf59d592ef]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyMethodDef_RawFastCallKeywords+0x316) [0x55719038f9b6]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyCFunction_FastCallKeywords+0x21) [0x55719038fa31]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x53e3) [0x5571903fc483]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0x2f9) [0x55719033e829]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallDict+0x1d5) [0x55719033f925]
/search/odin/wangjiawen/anaconda2/envs/python37/lib/python3.7/site-packages/torch/lib/libtorch_python.so(THPFunction_apply(_object*, _object*)+0x93d) [0x7fafabaeba6d]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyMethodDef_RawFastCallKeywords+0x1e4) [0x55719038f884]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyCFunction_FastCallKeywords+0x21) [0x55719038fa31]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x4e1d) [0x5571903fbebd]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0x2f9) [0x55719033e829]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallKeywords+0x387) [0x55719038f107]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x14e5) [0x5571903f8585]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0x2f9) [0x55719033e829]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallKeywords+0x387) [0x55719038f107]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x14e5) [0x5571903f8585]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallDict+0x10b) [0x55719033f85b]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_Call_Prepend+0x63) [0x55719035e4d3]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(PyObject_Call+0x6e) [0x557190350ffe]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x1e4a) [0x5571903f8eea]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0x2f9) [0x55719033e829]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallDict+0x1d5) [0x55719033f925]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_Call_Prepend+0x63) [0x55719035e4d3]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(+0x16be1a) [0x557190395e1a]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_FastCallKeywords+0x48b) [0x557190396ccb]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x52fe) [0x5571903fc39e]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0xc30) [0x55719033f160]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallDict+0x1d5) [0x55719033f925]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_Call_Prepend+0x63) [0x55719035e4d3]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(PyObject_Call+0x6e) [0x557190350ffe]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalFrameDefault+0x1e4a) [0x5571903f8eea]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyEval_EvalCodeWithName+0x2f9) [0x55719033e829]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyFunction_FastCallDict+0x1d5) [0x55719033f925]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_Call_Prepend+0x63) [0x55719035e4d3]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(+0x16be1a) [0x557190395e1a]
/search/odin/wangjiawen/anaconda2/envs/python37/bin/python3(_PyObject_FastCallKeywords+0x48b) [0x557190396ccb]


Thread 1 "python3" hit Catchpoint 1 (exception thrown), 0x00007fafac83e92d in __cxa_throw () from /lib64/libstdc++.so.6
```

It happens at:
```
16      namespace k2 {
17      void Renumbering::ComputeOld2New() {
18        NVTX_RANGE(K2_FUNC);
19        old2new_ = Array1<int32_t>(keep_.Context(), keep_.Dim() + 1);
20        ExclusiveSum(keep_, &old2new_);
21        num_new_elems_ = old2new_.Back(); // here, old2new_.dim_ == 27438
22        K2_CHECK_GE(num_new_elems_, 0);
23        K2_CHECK_LE(num_new_elems_, keep_.Dim());
24      }
```
Any idea?

**Comment by Jarvan-Wang** [comment]
For another exp(modeling syllable) with the code you offered, and reduce the max-duration from 100 to 20, it's works.
but the gpu memory it consume is high:
```
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:87:00.0 Off |                    0 |
| N/A   46C    P0   106W / 250W |  20943MiB / 22919MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by Jarvan-Wang** [comment]
even in syllable level model training(about 1k output nodes), without loading G, and the max-duration is very small, it's already consuming 20GB memory.
it must be an out-of-memory when decoding with a grammar.

I'm pretty sure that character level model(about 4k output-nodes) will not work in current code(it even cannot training).

**Comment by csukuangfj** [comment]
> I'm pretty sure that character level model(about 4k output-nodes) will not work in current code(it even cannot training).

From https://github.com/k2-fsa/k2/issues/739#issuecomment-843085650
> ... another way to reduce the size of the den graph would be to limit it to
only seen pairs of phone symbols.  But that would require some changes to
the code as our P matrix
would need to be ragged not square.

I am afraid your number of nodes (4k) is too large. The resulting `ctc_topo` and `P` are very large.
 `compose(ctc_topo, P)` is even larger.

**Comment by Jarvan-Wang** [comment]
> 
> 
> > I'm pretty sure that character level model(about 4k output-nodes) will not work in current code(it even cannot training).
> 
> From [k2-fsa/k2#739 (comment)](https://github.com/k2-fsa/k2/issues/739#issuecomment-843085650)
> 
> > ... another way to reduce the size of the den graph would be to limit it to
> > only seen pairs of phone symbols.  But that would require some changes to
> > the code as our P matrix
> > would need to be ragged not square.
> 
> I am afraid your number of nodes (4k) is too large. The resulting `ctc_topo` and `P` are very large.
> `compose(ctc_topo, P)` is even larger.

yes, i think so.

hmm, my syllable model training ran out of gpu memory after 1400 batches.

**Comment by danpovey** [comment]
I looked up your error at intersect_dense_pruned.cu:678, and it looks like the issue is not memory, it's that the neural net output dimension is too small by one.
(when you run the character-level model).

**Comment by danpovey** [comment]
Perhaps we should merge this?

**Pull request merged**
